# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bdda61028e017ce2fc7e7c392dcec3eb1c99e67adb91b3cbf99f34e08d7dd94f83cf4f251b52f1ef6debca9d46f38f0f50a183d02edd2ecb77906eccd2e030d

test:
  secret_key_base: 11d456da9752a1b7c0c1f9c203b218235a400afec28348cfad4dd3276573705c11c669093b90590540ac68d854ec975dbad95a325af1a5dbabe205fe929880b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
